name: Update CV PDF

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch and convert to PDF
        run: |
          set -euo pipefail
          test -n "${{ secrets.ONEDRIVE_DOCX_URL }}" || { echo "Missing ONEDRIVE_DOCX_URL secret" >&2; exit 1; }
          chmod +x scripts/fetch_cv_pdf.sh
          ./scripts/fetch_cv_pdf.sh "${{ secrets.ONEDRIVE_DOCX_URL }}"

      - name: Commit if changed
        run: |
          git add documents/Abdillah-Ilham-CV-Indonesia.pdf
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update CV PDF from OneDrive"
          git push
